version: '3'

services:

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  pg4admin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/postgres -schemas=public -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./flyway:/flyway/sql
    depends_on:
      - postgres

  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
